apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-deploy
  labels:
    app: quarkus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      name: quarkus-app-pod
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: quarkus-app-container
          image: pablofaalves/quarkus:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: postgres.default